### PR TITLE
placement: abort swap when destination location is fixed

### PR DESCRIPTION
**Pull request by acomodi**
This patch is to fix a situation for which a LOCed block can be swapped with other blocks during placement.

For instance, it is sometimes necessary to have the ability to constraint some critical blocks in specific SLICEs.

If the changes are accepted, I will push this on `wip/place_constraints` and generate a new `master+wip`

### CODE REVIEW

**Review by litghost — APPROVED** [review]
LGTM

**Comment by acomodi** [comment]
@litghost Probably it is worth waiting that the majority of the PRs open upstream that clean and optimize memory usage get merged.
Moreover, while rebasing each the wip branches on top of master I got quite a few conflicts.

**Comment by litghost** [comment]
> @litghost Probably it is worth waiting that the majority of the PRs open upstream that clean and optimize memory usage get merged.
> Moreover, while rebasing each the wip branches on top of master I got quite a few conflicts.

Yep

**Comment by acomodi** [comment]
This can be closed as it has been merged to the wip placement constraints branch.

**Pull request closed without merging**
