### PR TITLE
Heterogeneous master+wip

### PR DESCRIPTION
**Pull request by acomodi**
Included branches:
`wip/heterogeneous_tiles`

Deleted branches:
`wip/add_explicit_ports`
`wip/refactor_heap3`

### CODE REVIEW

**Review by litghost — APPROVED** [review]
LGTM, assuming CI is green

**Comment by acomodi** [comment]
`all_xc7` tests passes locally using this master+wip alongside with https://github.com/SymbiFlow/symbiflow-arch-defs/pull/1386

**Comment by litghost** [comment]
> `all_xc7` tests passes locally using this master+wip alongside with [SymbiFlow/symbiflow-arch-defs#1386](https://github.com/SymbiFlow/symbiflow-arch-defs/pull/1386)

Great, just fixed the Travis CI failure, and this is good to merge.

**Comment by acomodi** [comment]
> LGTM, assuming CI is green

Problem is that VtR + Symbiflow will never go green without changes to archdefs.

Travis CI on the other hand is complaining about some golden results that are not met. This does not happen on the heterogeneous tiles branch, so I may need to update the `wip/update_golden` branch

**Comment by litghost** [comment]
> so I may need to update the `wip/update_golden` branch

Yes

**Comment by acomodi** [comment]
Travis went green, merging.

**Pull request merged**
