### PR TITLE
Add check to ensure that clustering uses consistent modes.

### PR DESCRIPTION
**Pull request by litghost**

### CODE REVIEW

**Comment by mithro** [comment]
Could you add a little more explanation to this commit? I think this is checking for a case that doesn't seem like it should be possible, so I would like to understand what is going on better...

**Comment by litghost** [comment]
> Could you add a little more explanation to this commit? I think this is checking for a case that doesn't seem like it should be possible, so I would like to understand what is going on better...

Course its possible.  pb_types can support multiple nets.  If the clusterer chooses mode A for one net and mode B for another net, things can't work.  The original change you made ensured that pb_types modes within 1 net were consistent.  This ensures that all nets uses consistent modes.

**Comment by litghost** [comment]
To be clear, this PR was written because without it, output_clustering was throwing a mixed mode error.

**Comment by mithro** [comment]
Ahh, so that is the part I was missing. The cluster is choosing conflicting modes for different nets?

**Comment by litghost** [comment]
> Ahh, so that is the part I was missing. The cluster is choosing conflicting modes for different nets?

Yes.  It doesn't always do it, but when it does it appears to be deterministic.

**Comment by mithro** [comment]
I think I know what is causing it then. I need to restrict subsequent net routing to only modes which are valid for the existing routed nets. Previously this worked because only mode 0 could be used for route through.

Definitely think this check is good to have, so let's merge it.

**Comment by litghost** [comment]
> I think I know what is causing it then. I need to restrict subsequent net routing to only modes which are valid for the existing routed nets. Previously this worked because only mode 0 could be used for route through.

Ya, that is the more precise solution, but for now we need something that is working.  When the time comes to upstream, we'll need to demonstrate good performance.

**Pull request merged**
