### PR TITLE
Add initial FASM parameter support

### PR DESCRIPTION
**Pull request by litghost**
This is required for both FF ZINI support and DRAM INIT support.

This PR also fixes mixed mode clustering.

### CODE REVIEW

**Comment by mithro** [comment]
Can you split the PR into the clustering verse fasm?

**Comment by mithro** [comment]
Can you provide an example of the fasm parameter stuff? I'm unsure how it is actually used....

**Comment by litghost** [comment]
> Can you provide an example of the fasm parameter stuff? I'm unsure how it is actually used....

https://github.com/SymbiFlow/symbiflow-arch-defs/pull/277/files#diff-a9a61c6894ee54c6f7f55cf5637ab101R41

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/SymbiFlow/symbiflow-arch-defs/pull/277">Artix7 support in VPR by litghost · Pull Request #277 · SymbiFlow/symbiflow-arch-defs</a></strong></div><div>This adds support for artix7 with support for:

LUTs
FFs and latches
Carry chains
DRAM</div></blockquote>

**Comment by litghost** [comment]
> Can you split the PR into the clustering verse fasm?

Done

**Pull request merged**
