### PR TITLE
Fix v2x

### PR DESCRIPTION
**Pull request by acomodi**
This PR contains a fix for the v2x tests.

I had to solve regression tests golden results on `wip/update_golden`

### CODE REVIEW

**Comment by litghost** [comment]
Ci is still red?

**Review by litghost — CHANGES_REQUESTED** [review]
Ci is still red?

**Comment by acomodi** [comment]
I have an idea on how to fix the Strong regression tests.

The problem is VtR + arch-defs:

```
End of script. Logfile hash: 5b0fd873ed
CPU: user 0.02s system 0.00s, MEM: 25.53 MB total, 9.93 MB resident
Yosys 0.9+932 (git sha1 8fe9c84e, x86_64-conda_cos6-linux-gnu-gcc 1.23.0.449-a04d0 -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -fdebug-prefix-map=/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/yosys_1575648258825/work=/usr/local/src/conda/yosys-0.8_3923_g8fe9c84e -fdebug-prefix-map=/tmpfs/src/github/symbiflow-arch-defs/build/env/conda=/usr/local/src/conda-prefix -fPIC -Os)
Time spent: 49% 3x read_verilog (0 sec), 49% 2x opt_muxtree (0 sec), ...
[58/314] Generating golden.model.xml
[59/314] Generating carry.test.eblif
[60/314] Generating cblock.sim.v
[61/314] Generating cblock.model.golden.xml
[62/314] Generating golden.pb_type.xml
[63/314] Generating cblock.pb_type.golden.xml
FAILED: cd /tmpfs/src/github/symbiflow-arch-defs/build/utils/vlog/tests/carry && /tmpfs/src/github/symbiflow-arch-defs/build/env/conda/bin/yosys -p read_verilog\ carry.sim.v\;\ hierarchy\ -top\ CARRY\;\ techmap\ -map\ carry.techmap.merged.v\;\ flatten\;\ proc\;\ opt\;\ write_blif\ carry.test.eblif
ERROR: Can't open input file `carry.sim.v' for reading: No such file or directory
is_blackbox True has_modes? False
```

It fails on v2x tests for some missing files.

**Comment by litghost** [comment]
> I have an idea on how to fix the Strong regression tests.
> 
> The problem is VtR + arch-defs:
> 
> ```
> End of script. Logfile hash: 5b0fd873ed
> CPU: user 0.02s system 0.00s, MEM: 25.53 MB total, 9.93 MB resident
> Yosys 0.9+932 (git sha1 8fe9c84e, x86_64-conda_cos6-linux-gnu-gcc 1.23.0.449-a04d0 -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -fdebug-prefix-map=/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/yosys_1575648258825/work=/usr/local/src/conda/yosys-0.8_3923_g8fe9c84e -fdebug-prefix-map=/tmpfs/src/github/symbiflow-arch-defs/build/env/conda=/usr/local/src/conda-prefix -fPIC -Os)
> Time spent: 49% 3x read_verilog (0 sec), 49% 2x opt_muxtree (0 sec), ...
> [58/314] Generating golden.model.xml
> [59/314] Generating carry.test.eblif
> [60/314] Generating cblock.sim.v
> [61/314] Generating cblock.model.golden.xml
> [62/314] Generating golden.pb_type.xml
> [63/314] Generating cblock.pb_type.golden.xml
> FAILED: cd /tmpfs/src/github/symbiflow-arch-defs/build/utils/vlog/tests/carry && /tmpfs/src/github/symbiflow-arch-defs/build/env/conda/bin/yosys -p read_verilog\ carry.sim.v\;\ hierarchy\ -top\ CARRY\;\ techmap\ -map\ carry.techmap.merged.v\;\ flatten\;\ proc\;\ opt\;\ write_blif\ carry.test.eblif
> ERROR: Can't open input file `carry.sim.v' for reading: No such file or directory
> is_blackbox True has_modes? False
> ```
> 
> It fails on v2x tests for some missing files.

I would guess that is a missing dependency.  Can @kgugala take a look?

**Comment by litghost** [comment]
> I would guess that is a missing dependency. Can @kgugala take a look?

I've replicated the v2x test failure, and found at least one bug:
```
diff --git a/common/cmake/v2x.cmake b/common/cmake/v2x.cmake
index 934b873f..ba631e04 100644
--- a/common/cmake/v2x.cmake
+++ b/common/cmake/v2x.cmake
@@ -193,7 +193,7 @@ function(VPR_TEST_PB_TYPE)
     OUTPUT "${YOSYS_OUTPUT_BLIF}"
     DEPENDS
       ${YOSYS} ${YOSYS_TARGET}
-      ${DEPENS_EBLIF} ${TECHMAP_DEP}
+      ${DEPENDS_EBLIF} ${TECHMAP_DEP}
     COMMAND
     ${YOSYS} -p "read_verilog ${PB_TYPE_VERILOG}\; hierarchy -top ${VPR_TEST_PB_TYPE_TOP_MODULE}\; techmap -map ${PB_TYPE_TECHMAP}\; flatten\; proc\; opt\; write_blif ${YOSYS_OUTPUT_BLIF}"
     WORKING_DIRECTORY
```

**Comment by litghost** [comment]
I think https://github.com/SymbiFlow/symbiflow-arch-defs/pull/1228 fixes the V2X problem.  I'll merge that PR once the Travis run is complete.

**Comment by litghost** [comment]
Superceeded by #358

**Pull request closed without merging**
