### PR TITLE
Faster rr graph load

### PR DESCRIPTION
**Pull request by litghost**
Adds `wip/faster_rr_graph_read`, which drops the rr graph read time from 60 seconds to ~15 seconds.

### CODE REVIEW

**Comment by litghost** [comment]
FYI @duck2

**Review by mithro — APPROVED** [review]
This is just dropping the metadata reading, right?

LGTM.

**Comment by litghost** [comment]
> This is just dropping the metadata reading, right?
> 
> LGTM.

And adds an option to not run `check_rr_graph`, which means we can avoid repeating that check over and over again, and do it once during lookahead calc.

**Comment by acomodi** [comment]
Should we worry about Travis CI `C++ tests` failing? Most of them are fasm related, probably due to the `metadata` drop.

**Comment by litghost** [comment]
> Should we worry about Travis CI `C++ tests` failing? Most of them are fasm related, probably due to the `metadata` drop.

I broke the `fasm` unit tests, I know the fix and will apply it.

**Pull request merged**
